version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  qgis-server:
    image: kartoza/qgis-server:latest
    container_name: qgis-server
    ports:
      - "8080:80"
    depends_on:
      - postgis
    environment:
      QGIS_SERVER_LOG_LEVEL: 0
      QGIS_SERVER_LOG_FILE: /var/log/qgis/qgisserver.log
    volumes:
      - ./data:/data

  leaflet:
    image: nginx
    container_name: leaflet
    volumes:
      - ./leaflet:/usr/share/nginx/html
    ports:
      - "8081:80"

volumes:
  postgis_data:
